apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sendbird-uikit-sample-android-jetpack-compose
  description: UIKit for Android Jetpack Compose
  annotations:
    github.com/project-slug: sendbird/sendbird-uikit-sample-android-jetpack-compose
spec:
  type: sample
  lifecycle: production
  owner: dep-client-platform
  system: sendbird-uikit
